from django.db import models

class client_details(models.Model):
    name=models.CharField(max_length=200,null=True)
    email=models.EmailField(max_length=200,null=True)
    password=models.CharField(max_length=200,null=True)
    phone=models.CharField(max_length=200,null=True)
    incomeproof = models.FileField(upload_to='media/')
    currentsituation=models.CharField(max_length=200,null=True)
    clientid=models.CharField(max_length=200,null=True)
    login=models.BooleanField(default=False,null=True)
    logout=models.BooleanField(default=True,null=True)

class structuralrequirement(models.Model):
    square=models.PositiveIntegerField(null=True)
    rooms=models.CharField(max_length=200,null=True)
    wall1width=models.PositiveIntegerField(null=True)
    wall1height=models.PositiveIntegerField(null=True)
    wall2width=models.PositiveIntegerField(null=True)
    wall2height=models.PositiveIntegerField(null=True)
    extthick=models.PositiveIntegerField(null=True)
    intthick=models.PositiveIntegerField(null=True)
    roomwidth=models.PositiveIntegerField(null=True)
    cebs_wall2=models.CharField(max_length=200, null=True)
    bamboo_wall2=models.CharField(max_length=200, null=True)
    hempcrete_wall2=models.CharField(max_length=200, null=True)
    budget=models.PositiveIntegerField(null=True)
    clientid = models.CharField(max_length=200, null=True)
    cebs_quantity_predex=models.CharField(max_length=200, null=True)
    bamboo_beams_predex=models.CharField(max_length=200, null=True)
    hempcrete_kg_predex=models.CharField(max_length=200, null=True)
    cebs_quantity_predin=models.CharField(max_length=200, null=True)
    bamboo_beams_predin=models.CharField(max_length=200, null=True)
    hempcrete_kg_predin=models.CharField(max_length=200, null=True)
    cebs_quantity_predfloor=models.CharField(max_length=200, null=True)
    bamboo_beams_predfloor=models.CharField(max_length=200, null=True)
    hempcrete_kg_predfloor=models.CharField(max_length=200, null=True)
    cebs_quantity_predceil=models.CharField(max_length=200, null=True)
    bamboo_beams_predceil=models.CharField(max_length=200, null=True)
    hempcrete_kg_predceil=models.CharField(max_length=200, null=True)
    exwalcal=models.BooleanField(default=False,null=True)
    inwalcal = models.BooleanField(default=False, null=True)
    ceilcal = models.BooleanField(default=False, null=True)
    floorlen=models.PositiveIntegerField(null=True)
    floorwid=models.PositiveIntegerField(null=True)
    approve=models.BooleanField(default=False, null=True)
    report=models.FileField(upload_to='media/', null=True)

    corkvolumn_extwall1 = models.PositiveIntegerField(null=True)
    corkvolumn_extwall2=models.PositiveIntegerField(null=True)
    corksize=models.CharField(max_length=200, null=True)
    noofstraw1=models.PositiveIntegerField(null=True)
    noofstraw2 = models.PositiveIntegerField(null=True)
    balesize=models.CharField(max_length=200, null=True)
    calcork=models.BooleanField(default=False, null=True)
    calbale=models.BooleanField(default=False, null=True)
    approveext=models.BooleanField(default=False, null=True)

    noofshelve= models.PositiveIntegerField(null=True)
    calshelve = models.BooleanField(default=False, null=True)
    calcover= models.BooleanField(default=False, null=True)
    calfloor= models.BooleanField(default=False, null=True)
    excalculated=models.BooleanField(default=False, null=True)
    incalculated=models.BooleanField(default=False, null=True)
    structcalculate=models.BooleanField(default=False, null=True)
    f=models.BooleanField(default=True, null=True)

class interiorrequire(models.Model):
    bambooheight=models.PositiveIntegerField(null=True)
    bamboowidth=models.PositiveIntegerField(null=True)
    noofbamboo=models.PositiveIntegerField(null=True)
    clientid = models.CharField(max_length=200, null=True)
    extwall1coverarea=models.PositiveIntegerField(null=True)
    extwall2coverarea=models.PositiveIntegerField(null=True)
    intwallcoverarea=models.PositiveIntegerField(null=True)
    extwall1covercost = models.PositiveIntegerField(null=True)
    extwall2covercost = models.PositiveIntegerField(null=True)
    intwallcovercost = models.PositiveIntegerField(null=True)
    linoliumquantity=models.PositiveIntegerField(null=True)
    totalreport=models.FileField(upload_to='media/', null=True)
    genrep= models.BooleanField(default=False, null=True)
    approvetotrep=models.BooleanField(default=False, null=True)







