# Generated by Django 4.0.7 on 2024-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interior_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('poa', models.FileField(upload_to='media/')),
                ('interiorid', models.CharField(max_length=200, null=True)),
                ('login', models.BooleanField(default=False, null=True)),
                ('logout', models.BooleanField(default=True, null=True)),
                ('appint', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
